### ISSUE TITLE
There is not word "newses" in linguistic world

### ISSUE THREAD

**Issue by allenzhong** [SDM2016AUT/SERLER_production#6]
Rails follows linguistic rules, so  `newses` doesn't exist. It could be cause a lot of  problems when people use routes of Rails.

```ruby
#app/models/user.rb
has_many :newses, through: :notifications
```

I just corrected it in PR #3.

This is kind of bad model name in Rails. Most of time, we just use the word could be pluralised. 

Once you have any word, please verify it firstly.
In terminal and in project folder, type `rails console`. Then it enter console.

Then you could try like this

```bash
2.3.0 :001 > "news".pluralize
 => "news"
2.3.0 :002 > "news".singularize
 => "news"
``` 

Any name could you guys recommend?

**Comment by yuxiang8931** [comment]
Thank you for your tips

**Comment by yuxiang8931** [comment]
@allenzhong I intend to change it to "Headline". Is there a easy way to change Controller, Model, Migration and routes together?

**Comment by allenzhong** [comment]
There is a way here:
http://stackoverflow.com/questions/4826879/how-to-re-name-a-activerecord-model-which-can-automatically-change-the-table-nam

**Comment by allenzhong** [comment]
issue solved

**Comment by JohnnyJ0622** [comment]
Thanks for your information.
